spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB
      file-size-threshold: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "2482510236Gc!"
    url: jdbc:mysql://10.120.80.55:3306/proxyipcenter_boot?useUnicode=true&characterEncoding=utf8&socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 120000
      max-lifetime: 500000
      leak-detection-threshold: 450000
      pool-name: NotaryDbConnectionPool
      connection-test-query: select 1 from dual


server:
  port: 6048

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #  type-aliases-package: com.cp.common.bean
  #  config-location: classpath:mybatis-config.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
